"""Provider identity persistence contract."""

from datetime import datetime
from typing import Protocol
from uuid import UUID

from .models import ObservationScope, ProviderAccount, ProviderInstance


class ProviderIdentityRepository(Protocol):
    def create_instance(self, *, provider_type: str, instance_key: str, display_label: str | None = None, enabled: bool = True, now: datetime | None = None) -> ProviderInstance: ...
    def get_instance(self, instance_id: UUID) -> ProviderInstance | None: ...
    def get_instance_by_key(self, instance_key: str) -> ProviderInstance | None: ...
    def list_instances(self) -> tuple[ProviderInstance, ...]: ...
    def set_instance_enabled(self, instance_id: UUID, enabled: bool, *, now: datetime | None = None) -> ProviderInstance: ...

    def create_account(self, *, provider_instance_id: UUID, account_key: str, provider_native_id: str | None = None, display_label: str | None = None, enabled: bool = True, now: datetime | None = None) -> ProviderAccount: ...
    def get_account(self, account_id: UUID) -> ProviderAccount | None: ...
    def get_account_by_key(self, provider_instance_id: UUID, account_key: str) -> ProviderAccount | None: ...
    def list_accounts_for_instance(self, provider_instance_id: UUID) -> tuple[ProviderAccount, ...]: ...
    def set_account_enabled(self, account_id: UUID, enabled: bool, *, now: datetime | None = None) -> ProviderAccount: ...

    def create_scope(self, *, provider_instance_id: UUID, scope_key: str, provider_account_id: UUID | None = None, display_label: str | None = None, enabled: bool = True, now: datetime | None = None) -> ObservationScope: ...
    def get_scope(self, scope_id: UUID) -> ObservationScope | None: ...
    def get_scope_by_key(self, provider_instance_id: UUID, scope_key: str) -> ObservationScope | None: ...
    def list_scopes_for_instance(self, provider_instance_id: UUID) -> tuple[ObservationScope, ...]: ...
    def list_scopes_for_account(self, provider_account_id: UUID) -> tuple[ObservationScope, ...]: ...
    def set_scope_enabled(self, scope_id: UUID, enabled: bool, *, now: datetime | None = None) -> ObservationScope: ...
